key: googlespreadhseet
title: GoogleSpreadShhet
description: Conexión API para GoogleSpreadsheet.
author: Frederic Montes 
logo: https://static.requarks.io/logo/google.svg
color: red darken-1
website: https://console.developers.google.com/
isAvailable: true
useForm: false
scopes:
  - profile
  - email
  - openid
props:
  apikey:
    type: String
    title: APIKEY 
    hint: 
    order: 1
  clientSecret:
    type: String
    title: Client Secret
    hint: Application Client Secret
    order: 2
  hostedDomain:
    type: String
    title: Hosted Domain
    hint: (optional) Only for G Suite hosted domain. Leave empty otherwise.
    order: 3
