port: 3000 
bindIP: 0.0.0.0
db:
  type: postgres
  host: db
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki
logLevel: info
ssl:
  enabled: 1 
  port: 3443
  provider: letsencrypt
  domain: wiki.innova4social.org 
  subscriberEmail: frederic.montes@gmail.com 
