mutation ($id: Int!) {
    projectsRcmds {
       delete(id: $id) {
          responseResult {
            succeeded
            errorCode
            slug
             message
          }
      }
   }
}

