mutation($id: Int!, $title: String!, $content: String!, $updatedAt: Date!) {
  projectsRcmds {
    update(id: $id, title: $title, content: $content, updatedAt: $updatedAt) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
  }
 }
}

