query($id: Int!) {
  projectsRcmds {
    single(id:$id){
      id
      title
      content 
      createdAt
      updatedAt
      authorId
      authorName
      authorEmail
      arguments
      isnew
    }
  }
}

